- name: Delete NVIM
  hosts: localhost
  tasks:
    - name: Delete NVIM
      file:
        path: $HOME/.config/nvim/
        state: absent
    - name: Delete NVIM cache
      file:
        path: $HOME/.cache/nvim/
        state: absent
    - name: Delete NVIM state
      file:
        path: $HOME/.local/state/nvim/
        state: absent
