- name: Configure packages
  hosts: localhost
  tasks:
    - name: Configure Oh my Zsh (Mac)
      when: ansible_distribution == 'MacOSX'
      ansible.builtin.shell:
        cmd: |
          #/bin/bash
          sed -i '' '/ZSH_THEME/d' $HOME/.zshrc
          # VI mode
          if ! grep -q "bindkey -v" "$HOME/.zshrc"; then
            echo "bindkey -v" >> $HOME/.zshrc
          fi
