- name: Configure packages
  hosts: localhost
  tasks:
    - name: Create zshrc if it doesn't exists
      command: touch $HOME/.zshrc
      args:
        creates: $HOME/.zshrc
    - name: Configure Oh my Zsh (Linux)
      ansible.builtin.shell:
        cmd: |
          #/bin/bash
          sed -i '/ZSH_THEME/d' $HOME/.zshrc
    - name: Change shell to ZSH (Linux)
      become: yes
      ansible.builtin.shell:
        cmd: |
          #/bin/bash
          sudo chsh -s $(which zsh) $(whoami)
    - name: Configure Neovim
      import_tasks: packages/nvim/install.yaml
    - name: Configure Alacritty
      ansible.builtin.copy:
        src: ./packages/alacritty
        dest: $HOME/.config/
    - name: Configure dotfiles
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: $HOME/
      loop:
        - ./packages/dotfiles/.zshenv
        - ./packages/dotfiles/.tmux.conf
