- name: Install Flatpaks
  hosts: localhost
  tasks:
    - name: Flatpaks
      when: ansible_distribution != 'MacOSX'
      block:
        - name: Add the flathub flatpak repository remote to the user installation
          community.general.flatpak_remote:
            name: flathub
            state: present
            flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
            method: user
        - name: Flatpaks
          community.general.flatpak:
            state: present
            method: user
            name:
              - com.discordapp.Discord
              - org.videolan.VLC
              - sh.cider.Cider
              - us.zoom.Zoom
              - io.dbeaver.DBeaverCommunity
              - com.github.tchx84.Flatseal
              - com.github.jeromerobert.pdfarranger
              - org.mozilla.Thunderbird
              - it.mijorus.gearlever
              - md.obsidian.Obsidian
