- name: Install packages
  hosts: localhost
  #become: yes
  #become_method: su
  tasks:
    - name: Install MacOS packages
      when: ansible_distribution == 'MacOSX'
      block:
        - name: Ensure Hombrew packages
          community.general.homebrew:
            name:
              - nvim
              - tree-sitter
              - wget
              - lazygit
              - k0sctl
              - k9s
              - ripgrep
              - fd
            state: present

        - name: Ensure casks
          community.general.homebrew_cask:
            name:
              - dbeaver-community
              - docker
              - emacs
              - firefox
              - font-source-code-pro
              - graphql-playground
              - karabiner-elements
              - libreoffice
              - logseq
              - syncthing
              - vlc
              - vscodium
              - alacritty
              - wireshark
            state: present
    - name: Ensure packages
      when: ansible_distribution == 'Debian'
      apt:
        name:
          - neovim
          - python3-neovim
          - htop
          - docker
          - git
          - zsh
        state: present
    - name: Install oh my zsh
      ansible.builtin.shell:
        cmd: |
          sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
