- name: Install packages
  hosts: localhost
  #become: yes
  #become_method: su
  tasks:
    - name: Install MacOS packages
      when: ansible_distribution == 'MacOSX'
      block:
        - name: Ensure Hombrew packages
          community.general.homebrew:
            name:
              - nvim
              - tree-sitter
              - wget
              - lazygit
              - k0sctl
              - k9s
              - ripgrep
              - fd
            state: present

        - name: Ensure casks
          community.general.homebrew_cask:
            name:
              - dbeaver-community
              - docker
              - emacs
              - firefox
              - font-source-code-pro
              - graphql-playground
              - karabiner-elements
              - libreoffice
              - logseq
              - syncthing
              - vlc
              - vscodium
              - wireshark
            state: present
    - name: Ensure packages
      when: ansible_distribution == 'Debian'
      apt:
        name:
          - neovim
          - python3-neovim
          - htop
          - docker
        state: present
