- name: Install packages
  hosts: localhost
  tasks:
    - name: Install MacOS packages
      when: ansible_distribution == 'MacOSX'
      import_tasks: systems/macos.yaml
    - name: Install Fedora packages
      when: ansible_distribution == 'Fedora'
      become: true
      import_tasks: systems/fedora.yaml
    - name: Install PopOS packages
      when: ansible_distribution == 'Pop!_OS'
      become: true
      import_tasks: systems/popos.yaml
    - name: Install Ubuntu packages
      when: ansible_distribution == 'Ubuntu'
      become: true
      import_tasks: systems/ubuntu.yaml
    - name: Install Oh My Zsh
      block:
        - name: Check if Oh My Zsh is installed
          register: oh_my_zsh_installed
          stat:
            path: "{{ ansible_env.HOME }}/.oh-my-zsh"

        - name: Download Oh My Zsh
          when: not oh_my_zsh_installed.stat.exists
          ansible.builtin.shell:
            cmd: |
              sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
              zsh -c "git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k"
    - name: Install Mise
      block:
        - name: Check if Mise is installed
          register: mise_installed
          stat:
            path: "{{ ansible_env.HOME }}/.local/bin/mise"

        - name: Download Mise
          when: not mise_installed.stat.exists
          ansible.builtin.shell:
            cmd: |
              curl https://mise.run | sh
              $HOME/.local/bin/mise activate zsh >> $HOME/.zshrc

    - name: Install Fonts
      when: ansible_distribution != 'MacOSX'
      block:
        - name: Create font directory
          file:
            path: $HOME/.fonts
            state: directory

        - name: Install Nerd Font
          when: ansible_distribution != 'MacOSX'
          ansible.builtin.shell:
            cmd: |
              cd ~/.fonts && curl -fLO https://github.com/ryanoasis/nerd-fonts/raw/HEAD/patched-fonts/JetBrainsMono/Ligatures/Regular/JetBrainsMonoNerdFont-Regular.ttf && cd -
