- name: Install packages
  hosts: localhost
  #become: yes
  #become_method: su
  tasks:
    - name: Install MacOS packages
      when: ansible_distribution == 'MacOSX'
      block:
        - name: Ensure Hombrew packages
          community.general.homebrew:
            name:
              - nvim
              - tmux
              - tree-sitter
              - wget
              - lazygit
              - k0sctl
              - k9s
              - ripgrep
              - kubectl
              - fd
            state: present

        - name: Ensure casks
          community.general.homebrew_cask:
            name:
              - dbeaver-community
              - docker
              - emacs
              - firefox
              - font-source-code-pro
              - graphql-playground
              - karabiner-elements
              - libreoffice
              - logseq
              - syncthing
              - vlc
              - vscodium
              - alacritty
              - wireshark
            state: present
    - name: Ensure packages
      when: ansible_distribution == 'Debian'
      become: yes
      apt:
        name:
          - neovim
          - python3-neovim
          - htop
          - docker
          - docker.io
          - docker-compose
          - git
          - zsh
          - tmux
          - alacritty
          - fd-find
          - ripgrep
        state: present
    - name: Install oh my zsh
      register: oh_my_zsh
      changed_when: oh_my_zsh.stdout != "False"
      ansible.builtin.shell:
        cmd: |
          if [ -z ${ZSH+x} ]; then 
            sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
            echo "True"
          fi
            echo "False"
    - name: TPM (Tmux)
      ansible.builtin.shell:
        cmd: |
          git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
