- name: Install TLP
  hosts: localhost
  become: yes
  tasks:
    - name: Install TLP (Fedora)
      when: ansible_distribution == 'Fedora'
      dnf:
        name:
          - tlp
          - tlp-rdw
        state: present
    - name: Enable in systemd
      become: yes
      ansible.builtin.shell:
        cmd: |
          #/bin/bash
          systemctl enable --now tlp.service
          systemctl mask systemd-rfkill.service systemd-rfkill.socket
