- name: Add files, commit, and push changes to Git repository
  hosts: localhost # You can replace 'localhost' with your target host or group

  tasks:
    - name: Commit and push
      register: commit
      ansible.builtin.shell:
        cmd: |
          #/bin/bash
          if [[ -n $(git status -s packages/) ]]; then
            git commit -m "Updated packages: $(git diff --staged --name-only packages/ | cut -d '/' -f 2 | sort -u | awk '{printf "%s%s",sep,$0; sep=", "} END {print ""}')"
          fi
