- name: Add files, commit, and push changes to Git repository
  hosts: localhost # You can replace 'localhost' with your target host or group

  tasks:
    - name: Save nvim
      ansible.builtin.shell:
        cmd: |
          #/bin/bash
          cp -r $HOME/.config/nvim/ $CONFIGS_NVIM_DIR/
          git add --ignore-errors $CONFIGS_NVIM_DIR/
    - name: Dotfiles
      ansible.builtin.shell:
        cmd: |
          #/bin/bash
          cp $HOME/.zshenv $CONFIGS_DOTFILES_DIR/
          git add $CONFIGS_DOTFILES_DIR/
    - name: Commit and push
      register: commit
      ansible.builtin.shell:
        cmd: |
          #/bin/bash
          git commit -m "Updated packages: $(git diff --staged --name-only packages/ | cut -d '/' -f 2 | sort -u | awk '{printf "%s%s",sep,$0; sep=", "} END {print ""}')"
    - name: Echo commit
      debug:
        var: item
      loop:
        - "Return Code: {{ commit.rc }}"
        - "Standard Output: {{ commit.stdout }}"
        - "Standard Error: {{ commit.stderr }}"
        - "Task Changed: {{ commit.changed }}"

    #- name: Push changes to the Git repository
    #  ansible.builtin.git:
    #    repo: /path/to/your/git/repository
    #    push: yes
