- name: Installing ASDF
  import_playbook: asdf.yaml

- name: Install Elixir
  hosts: localhost
  vars:
    asdf_elixir_version: 1.17.2
    asdf_erlang_version: 27.0.1
  tasks:
    - name: ASDF Plugin Dependencies
      block:
        - name: MacOS
          when: ansible_distribution == 'MacOSX'
          community.general.homebrew:
            name:
              - unzip
              - kerl

    - name: ASDF Add Elixir Plugin
      ansible.builtin.shell:
        cmd: asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git

    - name: ASDF Add Erlang Plugin
      ansible.builtin.shell:
        cmd: asdf plugin add erlang https://github.com/asdf-vm/asdf-erlang.git

    - name: ASDF Install Erlang-{{ asdf_erlang_version }}
      ansible.builtin.shell:
        cmd: |
          #/bin/bash
          asdf install erlang {{ asdf_erlang_version }}

    - name: ASDF Install Elixir-{{ asdf_elixir_version }}
      ansible.builtin.shell:
        cmd: |
          #/bin/bash
          asdf install elixir {{ asdf_elixir_version }}

    - name: ASDF Configure Erlang-{{ asdf_erlang_version }}
      ansible.builtin.shell:
        cmd: asdf global erlang {{ asdf_erlang_version }}

    - name: ASDF Configure Elixir-{{ asdf_elixir_version }}
      ansible.builtin.shell:
        cmd: asdf global elixir {{ asdf_elixir_version }}
