- name: Installing ASDF
  import_playbook: asdf.yaml

- name: Install Go
  hosts: localhost
  vars:
    asdf_go_version: 1.22.6
  tasks:
    - name: ASDF Plugin Dependencies
      block:
        - name: MacOS
          when: ansible_distribution == 'MacOSX'
          community.general.homebrew:
            name:
              - coreutils

    - name: ASDF Add Golang Plugin
      ansible.builtin.shell:
        cmd: asdf plugin add golang https://github.com/asdf-community/asdf-golang.git

    - name: ASDF Install Go-{{ asdf_go_version }}
      ansible.builtin.shell:
        cmd: |
          #/bin/bash
          asdf install golang {{ asdf_go_version }}

    - name: ASDF Configure Go-{{ asdf_go_version }}
      ansible.builtin.shell:
        cmd: asdf global golang {{ asdf_go_version }}

    - name: Configure ZSH for GOROOT
      lineinfile:
        path: "{{ ansible_env.HOME }}/.zshenv"
        line: "{{ item }}"
      loop:
        - ". ~/.asdf/plugins/golang/set-env.zsh"
