install-asdf:
	ansible-playbook asdf.yaml --ask-become-pass
clojure:
	ansible-playbook clojure.yaml --ask-become-pass
go:
	ansible-playbook go.yaml
elixir:
	ansible-playbook elixir.yaml --ask-become-pass
