- name: Create directory if it does not exist
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/yabai"
    state: directory
    mode: "0755"

- name: Check if file exists
  stat:
    path: "{{ ansible_env.HOME }}/.config/yabai/yabairc"
  register: file_stat

- name: Create file if it doesn't exist
  file:
    path: "{{ ansible_env.HOME }}/.config/yabai/yabairc"
    state: touch
    mode: "0755"
  when: not file_stat.stat.exists

- name: "Add config"
  blockinfile:
    path: "{{ ansible_env.HOME }}/.config/yabai/yabairc"
    block: |
      yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
      sudo yabai --load-sa
      yabai -m rule --add app="^Logseq$" display=3 native-fullscreen=on sticky=on
      yabai -m rule --add app="^Google Chrome$" display=2 native-fullscreen=on manage=off
      yabai -m rule --add app="^Slack$" display=2 native-fullscreen=on manage=off
      yabai -m rule --add title="^Alacritty$" display=1 native-fullscreen=on manage=off
    marker: "# {mark} ANSIBLE MANAGED BLOCK - YABAI"
