- name: Create directory if it does not exist
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/skhd"
    state: directory
    mode: "0755"

- name: Check if file exists
  stat:
    path: "{{ ansible_env.HOME }}/.config/skhd/skhdrc"
  register: file_stat

- name: Create file if it doesn't exist
  file:
    path: "{{ ansible_env.HOME }}/.config/skhd/skhdrc"
    state: touch
    mode: "0755"
  when: not file_stat.stat.exists

- name: "Add config"
  blockinfile:
    path: "{{ ansible_env.HOME }}/.config/skhd/skhd"
    block: |
      ctrl - w : yabai -m display --focus 1
      ctrl - q : yabai -m display --focus 3
      ctrl - e : yabai -m display --focus 2
      ctrl - 1 : yabai -m query --windows | jq '.[] | select(.app == "Alacritty") | .id' | xargs -I {} yabai -m window --focus {}
      ctrl - 2 : yabai -m query --windows | jq '.[] | select((.app == "Google Chrome") and (.title | startswith("Starts with Title") | not)) | .id' | xargs -I {} yabai -m window --focus {}
      ctrl - 3 : yabai -m query --windows | jq '.[] | select(.app == "Slack") | .id' | xargs -I {} yabai -m window --focus {}
      ctrl - 4 : yabai -m query --windows | jq '.[] | select(.app == "Obsidian") | .id' | xargs -I {} yabai -m window --focus {}
      ctrl - 0 : yabai -m query --windows | jq '.[] | select(.app == "Music") | .id' | xargs -I {} yabai -m window --focus {}
    marker: "# {mark} ANSIBLE MANAGED BLOCK - SKHD"
