- name: Install packages
  hosts: localhost
  become: yes
  tasks:
    - name: Enable RPM Fusion
      when: ansible_distribution == 'Fedora'
      ansible.builtin.shell:
        cmd: |
          #/bin/bash
          sudo dnf install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
          sudo dnf config-manager --enable fedora-cisco-openh264
    - name: Ensure packages
      when: ansible_distribution == 'Fedora'
      dnf:
        name:
          - neovim
          - python3-neovim
          - htop
          - docker
          - git
          - fzf
          - g++
          - zsh
          - tmux
          - lazygit
          - alacritty
          - fd-find
          - ripgrep
          - gcc
          - kubernetes-client
          - cargo
          - nodejs
          - go
          - elixir
          - erlang
          - steam 
        state: present
