- name: Install Flatpaks
  hosts: localhost
  tasks:
    - name: Flatpaks
      when: ansible_distribution == 'Fedora'
      community.general.flatpak:
        name:
          - io.podman_desktop.PodmanDesktop
          - com.valvesoftware.Steam
          - sh.cider.Cider
          - org.freedesktop.Platform.openh264
          - dev.lizardbyte.app.Sunshine
