- name: Configure multilib
  become: yes
  blockinfile:
    path: "/etc/pacman.conf"
    block: |
      [multilib]
      Include = /etc/pacman.d/mirrorlist
    marker: "# {mark} ANSIBLE MANAGED BLOCK"

- name: Add user 'builder'
  become: yes
  block:
    - name: Add user 'builder'
      ansible.builtin.user:
        name: builder
        state: present
        shell: /bin/bash
        create_home: yes
    - name: Create /etc/sudoers.d/builder if it doesn't exist
      ansible.builtin.file:
        path: /etc/sudoers.d/builder
        state: touch
    - name: Configure builder user
      become: yes
      blockinfile:
        path: "/etc/sudoers.d/builder"
        block: |
          builder ALL=(ALL) NOPASSWD: /usr/bin/pacman, /usr/bin/makepkg
        marker: "# {mark} ANSIBLE MANAGED BLOCK"

- name: Update database
  become: yes
  ansible.builtin.shell: pacman -Sy

- name: Ensure packages Arch - Core
  become: yes
  pacman:
    name:
      - htop
      - fzf
      - base-devel
      - zsh
      - zip
      - unzip
      - wezterm
      - fd
      - ripgrep
      - vi
      - vim
      - wl-clipboard
      - ttf-jetbrains-mono-nerd
      - pandoc
      - openssh
      - flatpak
      - noto-fonts-cjk
      - otf-font-awesome
    state: present

- name: Ensure packages Arch - Dev
  become: yes
  pacman:
    name:
      - go
      - gcc
      - docker-compose
      - docker
      - git
      - fennel
      - luarocks
    state: present

- name: Ensure packages Arch - Video
  become: yes
  pacman:
    name:
      - mesa
      - libva
      - libvdpau-va-gl
    state: present

- name: Ensure packages Arch - Desktop apps
  become: yes
  pacman:
    name:
      - firefox
      - virtualbox
      - virtualbox-host-modules-arch
    state: present

- name: Ensure packages Arch - Recording/Editing
  become: yes
  pacman:
    name:
      - kdenlive
      - obs-studio
    state: present

- name: Ensure packages Arch - General
  become: yes
  pacman:
    name:
      - syncthing
    state: present

- name: Ensure packages Arch - Gaming
  become: yes
  pacman:
    name:
      - steam
    state: present

- name: Check install packages
  ansible.builtin.command: pacman -Qm
  ignore_errors: true
  register: installed_packages

- name: "Get 1Password GPG"
  become: yes
  become_user: builder
  ansible.builtin.shell: |
    curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --import

- name: "Install package"
  become: yes
  become_user: builder
  ansible.builtin.shell: |
    rm -rf /tmp/{{ item }}
    git clone https://aur.archlinux.org/{{ item }}.git /tmp/{{ item }}
    cd /tmp/{{ item }}
    makepkg -S --noconfirm
    makepkg -si --noconfirm
    #pkg=$(makepkg --packagelist)
    #sudo pacman -U $pkg
  when: item not in installed_packages.stdout
  with_items:
    - sunshine-bin
    - 1password
    - google-chrome
    - zoom
    - yay
    - vagrant
