- name: Check if RPM Fusion free repository is installed
  command: dnf repolist
  register: rpmfusion_free
  changed_when: false
- name: Enable RPM Fusion
  when: "'rpmfusion-free' not in rpmfusion_free.stdout"
  ansible.builtin.shell:
    cmd: |
      #/bin/bash
      dnf install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm -y
- name: Ensure packages
  dnf:
    name:
      - dnf-plugins-core
      - python3-neovim
      - htop
      - git
      - fzf
      - "@development-tools"
      - "@development-libs"
      - yq
      - jq
      - zsh
      - tmux
      - fd-find
      - ripgrep
      - openssl
      - openssl-devel
      - go
      - gcc
      - g++
      - luarocks
      - wl-clipboard
      - curl
      - alacritty
      - inotify-tools
      - ncurses-devel
      - gstreamer1-plugin-openh264
      - mozilla-openh264
    state: present
- name: Disable SELinux for directory
  ansible.builtin.shell:
    cmd: |
      #/bin/bash
      chcon -Rt svirt_sandbox_file_t {{ ansible_user_dir }}/workspace/
- name: Configure codecs
  ansible.builtin.shell:
    cmd: |
      #/bin/bash
      sudo dnf swap ffmpeg-free ffmpeg --allowerasing -y
      # AMD
      sudo dnf swap mesa-va-drivers mesa-va-drivers-freeworld -y
      sudo dnf swap mesa-vdpau-drivers mesa-vdpau-drivers-freeworld -y
- name: Configure extra repositories
  ansible.builtin.shell:
    cmd: |
      #/bin/bash
      # 1Password
      sudo rpm --import https://downloads.1password.com/linux/keys/1password.asc
      sudo sh -c 'echo -e "[1password]\nname=1Password Stable Channel\nbaseurl=https://downloads.1password.com/linux/rpm/stable/\$basearch\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=\"https://downloads.1password.com/linux/keys/1password.asc\"" > /etc/yum.repos.d/1password.repo'
      # Docker
      sudo dnf-3 config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
- name: Ensure extra packages
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - 1password
    state: present
    allowerasing: true
- name: Checking desktop
  shell: echo $XDG_CURRENT_DESKTOP
  register: desktop_env
- name: Ensure GNOME packages
  when: desktop_env.stdout == 'GNOME'
  dnf:
    state: present
    allowerasing: true
    name:
      - gnome-tweaks
      - gnome-extensions
