- name: Enable RPM Fusion
  ansible.builtin.shell:
    cmd: |
      #/bin/bash
      dnf install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm -y
      dnf config-manager --enable fedora-cisco-openh264
- name: Ensure packages
  dnf:
    name:
      - neovim
      - python3-neovim
      - htop
      - docker
      - git
      - fzf
      - g++
      - zsh
      - tmux
      - alacritty
      - fd-find
      - ripgrep
      - openssl
      - gcc
      - kubernetes-client
      - cargo
      - nodejs
      - go
      - elixir
      - erlang
      - steam
      - luarocks
    state: present
